### ISSUE TITLE
when the generated stored inside ./obj/ZeroQL IDE occurs problem

### ISSUE THREAD

**Issue by sabuydee** [byme8/ZeroQL#67] opened 2023-07-20 09:34 UTC
**Describe the bug**
Issue when the generated stored inside `./obj/ZeroQL` 

> notice this bug it not happen in project type `console app` but it happens like `blazor web assembly`, `web API`

Problem 1. IDE occurs problem `Duplicate definition 'ZeroQL.Client.ZeroQLClient'. Possibly missing keyword 'partial'` 
<img width="1155" alt="image" src="https://github.com/byme8/ZeroQL/assets/10388591/29222268-8a6e-4b24-83d3-cee9b01ec9a4">

Proplem 2. From above problem  when using `dotnet build` is error `The namespace 'ZeroQL.Client' already contains a definition for 'ZeroQLClient'`

**Workaround Solution (not available on version `6.0.0`)**
To use the config `output` option but not available on version `6.0.0`
but woking on version `4.0.0` follow schema https://raw.githubusercontent.com/byme8/ZeroQL/main/schema.verified.json

**How to Reproduce**
1. to create ZeroQL config file: `./config.zeroql.json` using command `dotnet zeroql config init`
2. add `output` option like
> {
  "$schema": "https://raw.githubusercontent.com/byme8/ZeroQL/main/schema.verified.json",
  "graphql": "./schema.graphql",
  "namespace": "ZeroQL.Client",
  "clientName": "ZeroQLClient",
  "output": "./Generated/GraphQL.g.cs"
}

**Expected behavior**
The generated client should be stored inside `./Generated/GraphQL.g.cs`
but is still stored inside `./obj/ZeroQL`

**Environment (please complete the following information):**
 - Nuget version [3.0.0]
 - IDE: [Rider]
 - .Net Version [6.0.400]

**Comment by jenschude** [comment] 2023-08-16 11:02
I had this issue when switching to the 6.x version. Had to remove the manual autobuild functionality and remove the "old" client. With 6.x the client will be auto generated and placed in the obj folder. So no need to have it committed in source.

**Comment by byme8** [comment] 2023-08-16 11:32
Sorry for delay.
As @jenschude said you don't need to set output path, in most cases, and store the generated client in git. It would be generated when you open IDE. However, I see that ability to set output path can be handy for more complex workflows. I started work on [here](https://github.com/byme8/ZeroQL/tree/feature/proper-build-task), but then The Baldur's Gate 3 happened.
I have plan to finish the feature this week.

**Comment by jenschude** [comment] 2023-08-16 11:34
Btw @byme8 I get schema validation errors, that the output property must be set. Strange thing for me is that I see your tests don't require it.

**Comment by jenschude** [comment] 2023-08-16 11:38
```
     1>Project "" on node 1 (build target(s)).
     1>GenerateQLClient:
         dotnet zeroql generate -c config.zeroql.json -o obj/ZeroQL/config.zeroql.json.g.cs
         Config file is not valid.
         Errors:
             config.zeroql.json [1:1]: Property Required at #/output
```

This is the build error happening when "cleaning" obj folder or in a fresh checkout like my CI pipeline. Adding the `output` property to the schema file solves it.

**Comment by byme8** [comment] 2023-08-16 11:39
Will have a look at it.

**Comment by byme8** [comment] 2023-08-18 05:48
@sabuydee Checkout 6.1.0-preview.1. The problem 2 should be fixed. Now it is take to account output property in config.
About the problem 1. I was not able to reproduce it. Can you tell more about your setup and how you were able to reproduce it?

@jenschude Try this version. I have tried to see validation error by deleting the obj folder and executing `` dotnet build `` and I was not able to reproduce it. Maybe you forget to update `` ZeroQL.Cli `` tool?

**Comment by jenschude** [comment] 2023-08-31 08:31
You were right. Still had the 5.x used in the dotnet tools 🤦

**Comment by sabuydee** [comment] 2023-09-09 20:17
@byme8 i have test 6.1.0-preview my machine it's working.

sorry that long time for answer
thank you so much.

**Comment by janushannesarson** [comment] 2023-09-13 15:01
> @sabuydee Checkout 6.1.0-preview.1. The problem 2 should be fixed. Now it is take to account output property in config. About the problem 1. I was not able to reproduce it. Can you tell more about your setup and how you were able to reproduce it?

I don't think problem 2 is fixed?

I have a:

"output": "./ZeroQL/GraphQL.g.cs"

In my config.zeroql.json, but it won't genereate the file.

Instead it keeps generating two sepperate files, one in

 obj/ZeroQL/bin/Debug/net7.0/config.zeroql.json.g.cs
 
and one in:

obj/ZeroQL/config.zeroql.json.g.cs , which causes build errors:

  config.zeroql.json.g.cs(16, 18): [CS0101] The namespace 'ZeroQL.Client' already contains a definition for 'ZeroQLClient'

**Comment by byme8** [comment] 2023-09-13 20:55
@janushannesarson Have you updated the ZeroQL CLI and the ZeroQL nuget package in the project?

For me it looks like you forget to update the Nuget package. Also, close and open VS may help. It has issues when source generator and targets and changed after package update.

**Comment by janushannesarson** [comment] 2023-09-15 10:36
@byme8 Should I have a the "6.1.0-preview"  version?

**Comment by byme8** [comment] 2023-09-15 10:40
Yes, use 6.1.0-preview.1 version in CLI and Nuget package. Also, I thought about it again, and you can try to delete ./obj/ZeroQL/bin/Debug/net7.0/config.zeroql.json.g.cs once. Maybe it is an old file from a previous execution. If it is true, then with 6.1.0-preview.1. It should not be generated again.

**Comment by janushannesarson** [comment] 2023-09-15 12:58
Seems to be working, thanks :)

**Closed** 2023-10-23 12:27 UTC
Labels: bug
